# Site settings
title: Eat Nap Code
email: kirsten@eml.cc
description: One womans search for, ehm, everything > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eatnapcode.com" # the base hostname & protocol for your site
twitter_username: kapow_zap
github_username:  oknono

# Build settings
markdown: kramdown
paginate: 5
