# Site settings
title: Eat Nap Code
email: kirsten@eml.cc
description: One womans search for, ehm, everything  
url: "http://eatnapcode.com" # the base hostname & protocol for your site
twitter_username: kapow_zap
github_username:  oknono
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
